// Generated by CoffeeScript 1.10.0
(function() {
  var ResourceSchema, User;

  ResourceSchema = require('resource-schema');

  User = require('local_modules/models/user');

  module.exports = new ResourceSchema(User, {
    '_id': '_id',
    'firstName': 'firstName',
    'lastName': 'lastName',
    'email': 'email',
    'level': 'level',
    'points': 'points',
    'credits': 'credits',
    'roles': 'roles'
  });

}).call(this);
