// Generated by CoffeeScript 1.10.0
(function() {
  var JSONSchema, unionized;

  unionized = require('unionized');

  JSONSchema = require('./schema');

  module.exports = unionized.JSONSchemaFactory(JSONSchema);

}).call(this);
