// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, levelHelper, logger;

  logger = require('local_modules/logger');

  levelHelper = require('local_modules/level');

  Promise = require('bluebird');

  module.exports = function(schema) {
    return schema.pre('save', function(next) {
      var Challenge;
      Challenge = require('local_modules/models/challenge');
      return Promise["try"]((function(_this) {
        return function() {
          if (_this.isNew) {
            return Promise.all([
              Challenge.createInitialChallenges({
                user: _this
              }), Challenge.createChallenge('level', {
                user: _this
              })
            ]);
          }
        };
      })(this)).then((function(_this) {
        return function() {
          return next();
        };
      })(this)).then(null, next);
    });
  };

}).call(this);
