// Generated by CoffeeScript 1.10.0
(function() {
  var _, convict, path;

  _ = require('lodash');

  convict = require('convict');

  path = require('path');


  /*
  base convict settings.
  can extend with app-specific settings.
  returns POJO.
   */

  module.exports = (function() {
    var convictConfig, envConfig, err, error, ref, settings, version;
    convictConfig = require('./config');
    settings = convict(convictConfig);
    envConfig = (ref = require('./defaults_per_env')[settings.get('env')]) != null ? ref : {};
    settings.load(envConfig);
    if (settings.get('server.url') == null) {
      settings.set('server.url', "http://localhost:" + (settings.get('server.port')));
    }
    try {
      version = require(path.join(process.cwd(), 'version'));
      settings.load({
        sha: version
      });
    } catch (error) {
      err = error;
      if (err.code !== 'MODULE_NOT_FOUND') {
        throw err;
      }
    }
    settings.validate();
    return settings.root();
  })();

}).call(this);
