const MODULE_NAME = 'userPieces'

export const PIECE_REQUEST = `${MODULE_NAME}/PIECE_REQUEST`
export const PIECE_SUCCESS = `${MODULE_NAME}/PIECE_SUCCESS`
export const PIECE_FAILURE = `${MODULE_NAME}/PIECE_FAILURE`

export const USERPIECE_REQUEST = `${MODULE_NAME}/USERPIECE_REQUEST`
export const USERPIECE_SUCCESS = `${MODULE_NAME}/USERPIECE_SUCCESS`
export const USERPIECE_FAILURE = `${MODULE_NAME}/USERPIECE_FAILURE`

export const LEVEL_REQUEST = `${MODULE_NAME}/LEVEL_REQUEST`
export const LEVEL_SUCCESS = `${MODULE_NAME}/LEVEL_SUCCESS`
export const LEVEL_FAILURE = `${MODULE_NAME}/LEVEL_FAILURE`
