// Generated by CoffeeScript 1.10.0
(function() {
  var Notification, ResourceSchema, _;

  _ = require('lodash');

  ResourceSchema = require('resource-schema');

  Notification = require('local_modules/models/notification');

  module.exports = new ResourceSchema(Notification);

}).call(this);
