// Generated by CoffeeScript 1.10.0
(function() {
  var ResourceSchema, UserChallenge;

  ResourceSchema = require('resource-schema');

  UserChallenge = require('local_modules/models/challenge');

  module.exports = new ResourceSchema(UserChallenge);

}).call(this);
