// Generated by CoffeeScript 1.10.0

/*
Entry point for web process
 */

(function() {
  var onceUpon, server;

  require('local_modules/boot');

  onceUpon = require('once-upon');

  server = require('./server');

  server.start(function(err) {
    if (err) {
      console.error("Failed to start server", err);
    }
    return onceUpon('SIGINT SIGTERM', process, function() {
      return server.stop(function(err) {
        if (err) {
          return console.error("Failed to stop server", err);
        }
      });
    });
  });

}).call(this);
